apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: service-nodeport
spec:
  type: NodePort           #Loại service: NodePort
  selector:                #Khai báo rule để lọc các Pod mà service sẽ forward connection tới
    app: nginx
  ports:
    - targetPort: 80       #Là port của Pod, service sẽ chuyển tiếp kết nối vào đây
      port: 80             #Là port được mở của Service. Client sẽ kết nối với Service qua port
      nodePort: 30077      #Port được mở trên tất cả các node để nhận request cho service
